Repository M0IM/FE-M, pull requests merged in 2024-12, with the labels that each got.

#219 [MM-320] Feat: 모임 스페이스 네비게이션 구조 변경
  src/components/screens/MoimBoardStackScreens/BoardPostPreview.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfo.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfoContainer.tsx
  src/components/screens/MoimDetailScreen/MoimContentsPreview.tsx
  src/components/screens/MoimDetailScreen/MoimMembersScrollView.tsx
  src/navigators/constants/stack.ts
  src/navigators/stack/HomeStackNavigator.tsx
  src/navigators/stack/MoimPostStackNavigator.tsx
  src/navigators/stack/MoimSpaceNavigator.tsx
  src/navigators/stack/MoimStackNavigator.tsx
  src/navigators/stack/UserProfileStackNavigator.tsx
  src/navigators/tab/MoimTopTabNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimBoardStackScreens/MoimMemberDetailProfileScreen.tsx
  src/screens/MoimBoardStackScreens/MoimParticipantMoimScreen.tsx
  src/screens/MoimBoardStackScreens/MoimUserReviewScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/screens/UserProfileScreens/UserDetailProfileScreen.tsx
  src/screens/UserProfileScreens/UserParticipantMoimScreen.tsx
Labels: ✨ Feat, 🔨 Refactor

#223 [MM-324] Deploy: 안드로이드 버전 업데이트 및 아이콘 변경
  android/app/build.gradle
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: 🌏 Deploy

#229 [MM-328] 구글 배너 광고 삽입
  .yarn/install-state.gz
  app.json
  ios/MOIM.xcodeproj/project.pbxproj
  ios/MOIM/PrivacyInfo.xcprivacy
  ios/Podfile.lock
  package.json
  src/components/@common/ScreenBannerAd/ScreenBannerAd.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  yarn.lock
Labels: ✨ Feat, 🌏 Deploy

#231 [MM-329] 안드로이드 1.1.4 버전 배포 세팅
  android/app/build.gradle
  android/app/proguard-rules.pro
  ios/MOIM.xcodeproj/project.pbxproj
Labels: 🐞 bug, ✨ Feat, 🌏 Deploy
