Repository M0IM/FE-M, pull requests merged in 2024-09, with the labels that each got.

#155 [MM-227] Feat: 모임 스페이스 & 메인화면 스타일 버그 및 로직 수정
  ios/MOIM.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/components/@common/CustomTabBar/CustomTabBar.tsx
  src/components/home/PostPreviewBox/PostPreviewBox.tsx
  src/components/screens/FeedTabScreens/Card.tsx
  src/components/screens/FeedTabScreens/MoimFeedPreview.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/components/screens/MoimDetailScreen/MoimInfoContainer.tsx
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimManagementScreens/DelegationAuthorityScreen.tsx
  src/types/dtos/moim.ts
  yarn.lock
Labels: 🐞 bug, ✨ Feat, 🎨 Style

#157 [MM-228] Feat: 메인 화면 스켈레톤 UI 구현
  src/components/screens/FeedTabScreens/MoimFeedPreview.tsx
  src/components/screens/FeedTabScreens/MoimHappeningEvent.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/components/screens/FeedTabScreens/skeleton/MoimFeedPreviewSkeleton.tsx
  src/components/screens/FeedTabScreens/skeleton/MoimHappeningEventSkeleton.tsx
  src/components/screens/FeedTabScreens/skeleton/MoimMyEventSkeleton.tsx
  src/components/screens/FeedTabScreens/skeleton/MoimScheduleEventSkeleton.tsx
Labels: ✨ Feat

#158 [MM-226] CreateTodo api 연결, MoimCreateTodoScreen 구현
  .yarn/install-state.gz
  App.tsx
  ios/MOIM.xcodeproj/project.pbxproj
  ios/MOIM/Info.plist
  src/apis/todo.ts
  src/apis/user.ts
  src/components/@common/CustomTabBar/CustomTabBar.tsx
  src/components/screens/MoimBoardStackScreens/ReadersBottomSheet.tsx
  src/constants/storageKeys/keys.ts
  src/hooks/useTodo.ts
  src/navigators/stack/MoimManagementStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimManagementScreens/MoimCreateTodoScreen.tsx
  src/screens/MoimManagementScreens/MoimManageListScreen.tsx
  src/screens/MoimManagementScreens/components/ReaderPickerBottomSheet.tsx
  src/types/dtos/todo.ts
  src/utils/validate.ts
Labels: ✨ Feat

#162 [MM-230] ToDo 관련 API 연결, Screen 구현
  .yarn/install-state.gz
  src/apis/todo.ts
  src/components/@common/CustomTabBar/CustomTabBar.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/constants/storageKeys/keys.ts
  src/hooks/queries/AuthScreen/useAuth.ts
  src/hooks/useTodo.ts
  src/navigators/stack/MoimManagementStackNavigator.tsx
  src/navigators/stack/MyStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimManagementScreens/MoimCreateTodoScreen.tsx
  src/screens/MoimManagementScreens/MoimGetTodoScreen.tsx
  src/screens/MoimManagementScreens/MoimManageListScreen.tsx
  src/screens/MoimManagementScreens/MoimTodoDetailScreen.tsx
  src/screens/MoimManagementScreens/MyMoimAssignmentCheckScreen.tsx
  src/screens/MoimManagementScreens/components/ParticipantList.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/screens/MyStackScreens/MyAssignmentTodoScreen.tsx
  src/screens/MyStackScreens/MyHomeScreen.tsx
  src/types/dtos/todo.ts
  yarn.lock
Labels: ✨ Feat

#165 [MM-240] Todo API 연결 및 스크린 구현
  ios/MOIM.xcodeproj/project.pbxproj
  src/apis/todo.ts
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/hooks/queries/AuthScreen/useAuth.ts
  src/hooks/useTodo.ts
  src/navigators/stack/HomeStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimCalenderStackScreens/MoimPlanDetailScreen.tsx
  src/screens/MoimManagementScreens/MoimCreateTodoScreen.tsx
  src/screens/MoimManagementScreens/MoimManageListScreen.tsx
  src/screens/MoimManagementScreens/MoimTodoDetailScreen.tsx
  src/screens/MoimManagementScreens/components/ParticipantList.tsx
  src/screens/MoimStackScreens/CalendarTodoDetailScreen.tsx
  src/stores/useTodoStore.ts
  src/types/dtos/todo.ts
Labels: ✨ Feat

#167 [MM-243] ToDo 추가 API 연결, 서버 변경사항 반영
  ios/MOIM.xcodeproj/project.pbxproj
  src/apis/todo.ts
  src/hooks/useTodo.ts
  src/navigators/stack/MoimManagementStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimManagementScreens/MoimAddMemberScreen.tsx
  src/screens/MoimManagementScreens/MoimCreateTodoScreen.tsx
  src/screens/MoimManagementScreens/MoimDeleteMemberScreen.tsx
  src/screens/MoimManagementScreens/MoimTodoDetailScreen.tsx
  src/screens/MoimManagementScreens/MyMoimAssignmentCheckScreen.tsx
  src/screens/MyStackScreens/MyAssignmentTodoScreen.tsx
Labels: ✨ Feat

#170 [MM-239] Feat: reject 사유 해결 & 모임 관련 버그 및 로직 수정
  src/apis/moim.ts
  src/components/calendar/ActiveMoimCard.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfo.tsx
  src/components/screens/MoimDetailScreen/MoimDashboardContainer.tsx
  src/constants/screens/MoimDetailScreens/age.ts
  src/constants/screens/MoimSearchScreen/CategoryList.ts
  src/constants/screens/MyScreens/MyPrivacyPolicyScreen.ts
  src/hooks/queries/MoimHomeScreen/useGetInfiniteMyActiveMoim.ts
  src/hooks/useDropdown.ts
  src/navigators/stack/MoimManagementStackNavigator.tsx
  src/navigators/stack/MoimPostStackNavigator.tsx
  src/navigators/stack/MyStackNavigator.tsx
  src/screens/AuthStackScreens/PrivacyPolicyScreen.tsx
  src/screens/AuthStackScreens/ServiceTermScreen.tsx
  src/screens/AuthStackScreens/SignupLastStepScreen.tsx
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostEditScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  src/screens/MoimBoardStackScreens/MoimUserReviewScreen.tsx
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimManagementScreens/MoimEditInfoScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/screens/MoimStackScreens/MoimHomeScreen.tsx
  src/screens/UserProfileScreens/UserReviewScreen.tsx
  src/stores/useMoimInfoStore.ts
  src/stores/useMoimPostStore.ts
  src/types/dtos/moim.ts
  src/utils/index.ts
  src/utils/moim.ts
Labels: 🐞 bug, ✨ Feat, 🎨 Style

#173 [MM-249] Calendar ToDo Detail Screen, useEmail 활용, 이메일 전송 기능.
  src/apis/email.ts
  src/apis/index.ts
  src/components/@common/CalendarEventList/CalendarEventList.tsx
  src/components/@common/Popover/PopoverMenu/PopoverMenu.tsx
  src/components/calendar/CalendarEvent/CalendarEvent.tsx
  src/components/home/SchduleCard/ScheduleCard.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/hooks/useEmail.ts
  src/navigators/stack/HomeStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimStackScreens/CalendarTodoDetailScreen.tsx
  src/screens/MyStackScreens/MyContactScreen.tsx
  src/types/dtos/calendar.ts
  src/utils/validate.ts
Labels: ✨ Feat

#174 [MM-253] Feat: 모임 관련 변경 API 반영
  src/apis/post.ts
  src/apis/search.ts
  src/components/home/PostPreviewBox/PostPreviewBox.tsx
  src/components/screens/MoimBoardStackScreens/ReadersBottomSheet.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfo.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfoContainer.tsx
  src/constants/screens/MoimSearchScreen/CategoryList.ts
  src/hooks/queries/MoimSearchScreen/useGetSeachInfiniteMoimList.ts
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  src/screens/MoimSearchScreens/MoimSearchScreen.tsx
  src/types/dtos/post.ts
  src/types/enums/index.ts
Labels: ✨ Feat, 🎨 Style

#178 [MM-257] PushNotification Foreground 상태 위한 Channel 설정
  .yarn/install-state.gz
  App.tsx
  src/apis/calendar.ts
  src/apis/moim.ts
  src/components/calendar/CalendarEvent/CalendarEvent.tsx
  src/navigators/root/RootNavigator.tsx
  src/utils/header.ts
Labels: ✨ Feat

#177 [MM-256] Feat: 모임 찾기 및 그 외 모임/내 정보 관련 수정 사항 반영
  src/apis/moim.ts
  src/components/@common/Avatar/Avatar.tsx
  src/components/@common/ProfileCard/ProfileCard.tsx
  src/components/calendar/CalendarEvent/CalendarEvent.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/components/screens/FeedTabScreens/ScheduleColorPalette.tsx
  src/components/screens/MoimDetailScreen/MoimMembersScrollView.tsx
  src/components/screens/MoimSearchScreens/skeleton/MoimSearchScreenSkeleton.tsx
  src/components/screens/MyStackScreens/MyProfileCard.tsx
  src/constants/screens/FeedStackScreens/MoimRoleList.ts
  src/hooks/queries/MoimHomeScreen/useGetInfiniteMyActiveMoim.ts
  src/hooks/queries/MyScreen/useGetDetailProfile.ts
  src/hooks/queries/MyScreen/useGetProfile.ts
  src/navigators/constants/stack.ts
  src/navigators/stack/MyStackNavigator.tsx
  src/navigators/stack/TodoStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/CalendarStackScreens/CalendarHomeScreen.tsx
  src/screens/MoimBoardStackScreens/MoimMemberDetailProfileScreen.tsx
  src/screens/MoimSearchScreens/MoimSearchScreen.tsx
  src/screens/MoimStackScreens/CalendarTodoDetailScreen.tsx
  src/screens/MoimStackScreens/MoimHomeScreen.tsx
  src/screens/MoimStackScreens/components/DetailItem.tsx
  src/screens/MyStackScreens/MyDetailProfileScreen.tsx
  src/screens/MyStackScreens/MyHomeScreen.tsx
  src/screens/MyStackScreens/MyMoimJoinStatusScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/MyAssignmentTodoScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/MyTodoDetailScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/TodoAddMemberScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/TodoCreateScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/TodoMemberDeleteScreen.tsx
  src/screens/UserProfileScreens/UserDetailProfileScreen.tsx
  src/types/dtos/moimManage.ts
  src/types/enums/index.ts
Labels: 🐞 bug, ✨ Feat, 🎨 Style

#180 [MM-263] PushNotification 무한 재귀 현상 해결
  .yarn/install-state.gz
  App.tsx
  ios/MOIM/AppDelegate.mm
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
Labels: 🐞 bug, ✨ Feat

#182 [MM-269] Feat: 모임 신청 상태/활동 중인 모임/탈퇴 부분 수정
  ios/Podfile.lock
  src/apis/user.ts
  src/constants/screens/MyScreens/MoimJoinStatus.ts
  src/hooks/queries/MyScreen/useGetInfiniteMoimJoinRequest.ts
  src/screens/MoimStackScreens/MoimHomeScreen.tsx
  src/screens/MyStackScreens/MyMoimJoinStatusScreen.tsx
  src/screens/MyStackScreens/RevokeMoimScreen.tsx
  src/types/dtos/user.ts
  src/types/enums/index.ts
  yarn.lock
Labels: 🐞 bug, ✨ Feat, 🎨 Style

#184 [MM-274] 배포 전 에러 핸들링
  .yarn/install-state.gz
  App.tsx
  ios/Podfile.lock
  src/components/screens/FeedTabScreens/MoimHappeningEvent.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/CommentInput.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfo.tsx
  src/hooks/queries/MoimBoard/usePost.ts
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  src/screens/MoimManagementScreens/MoimCreateTodoScreen.tsx
  src/screens/MoimManagementScreens/MoimTodoDetailScreen.tsx
  src/screens/MoimSearchScreens/MoimSearchScreen.tsx
  src/screens/NewFeedStack/NewFeedHomeScreen.tsx
  yarn.lock
Labels: 🐞 bug, ✨ Feat, 🌏 Deploy

#186 [MM-278] 모임장 -> 모임원 탈퇴 기능 구현
  .yarn/install-state.gz
  src/apis/moimManage.ts
  src/apis/todo.ts
  src/components/@common/CustomTabBar/CustomTabBar.tsx
  src/hooks/queries/MoimManagement/useMoimManagement.ts
  src/navigators/stack/MoimManagementStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/CalendarStackScreens/CalendarHomeScreen.tsx
  src/screens/MoimManagementScreens/MoimCreateTodoScreen.tsx
  src/screens/MoimManagementScreens/MoimManageListScreen.tsx
  src/screens/MoimManagementScreens/MoimOutMemberScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/TodoCreateScreen.tsx
Labels: 🐞 bug, ✨ Feat

#189 [MM-283] 회원 탈퇴 기능 구현
  src/apis/moimManage.ts
  src/hooks/queries/MoimManagement/useMoimManagement.ts
  src/screens/MoimManagementScreens/MoimOutMemberScreen.tsx
Labels: ✨ Feat

#190 [MM-281] Feat: 유저 프로필 수정 화면 로직 수정
  src/screens/MyStackScreens/MyProfileEditScreen.tsx
Labels: 🐞 bug, ✨ Feat

#196 [MM-287] 서버 변경사항 반영 및 배포 이전 에러 핸들링
  src/apis/calendar.ts
  src/apis/moim.ts
  src/apis/moimManage.ts
  src/components/post/PostForm.tsx
  src/components/space/DetailSchedules/DetailSchedules.tsx
  src/constants/storageKeys/keys.ts
  src/hooks/queries/MoimManagement/useMoimManagement.ts
  src/hooks/useMoim.ts
  src/navigators/tab/MoimTopTabNavigator.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanDetailScreen.tsx
  src/screens/MoimManagementScreens/MoimManageListScreen.tsx
  src/screens/MoimManagementScreens/MoimOutMemberScreen.tsx
  src/screens/MoimStackScreens/CalendarParticipantDetailScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/types/dtos/moim.ts
Labels: 🐞 bug, ✨ Feat, 🔨 Refactor, 🌏 Deploy

#195 [MM-285] Feat: 댓글 삭제 로직 처리
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostRecommentContainer.tsx
  src/types/dtos/post.ts
Labels: 🐞 bug, ✨ Feat

#198 [MM-293] Feat: mutate 관련 중복 요청 방지 이슈
  App.tsx
  src/components/calendar/CalendarPostForm.tsx
  src/components/post/PostForm.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/CommentInput.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfo.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostRecommentContainer.tsx
  src/components/screens/MoimHomeScreens/MoimJoinRequestScrollView.tsx
  src/components/screens/MoimHomeScreens/MoimPermissionScrollView.tsx
  src/hooks/queries/MoimManagement/useMoimManagement.ts
  src/hooks/useThrottle.ts
  src/screens/AuthStackScreens/AuthHomeScreen.tsx
  src/screens/AuthStackScreens/SignupLastStepScreen.tsx
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostReviewScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanDetailScreen.tsx
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimManagementScreens/MoimAddMemberScreen.tsx
  src/screens/MoimManagementScreens/MoimCreateTodoScreen.tsx
  src/screens/MoimManagementScreens/MoimDeleteMemberScreen.tsx
  src/screens/MoimManagementScreens/MoimTodoDetailScreen.tsx
  src/screens/MoimManagementScreens/components/ParticipantList.tsx
  src/screens/MoimStackScreens/CalendarTodoDetailScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/screens/MyStackScreens/EditAlertScreen.tsx
  src/screens/MyStackScreens/MyContactScreen.tsx
  src/screens/MyStackScreens/MyProfileEditScreen.tsx
  src/utils/batchRequestOf.ts
Labels: 🐞 bug, ✨ Feat

#202 MM-301 프로필 수정 기능 변경, 성별 / 지역 / 연령 미 제공시 모임 홈 스페이스 에러 해결
  App.tsx
  src/apis/user.ts
  src/components/screens/MoimDetailScreen/MoimDashboardContainer.tsx
  src/screens/AuthStackScreens/SignupLastStepScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/screens/MyStackScreens/MyDetailProfileScreen.tsx
  src/screens/MyStackScreens/MyProfileEditScreen.tsx
  src/stores/useMoimCalendarStore.ts
  src/types/dtos/moim.ts
  src/types/dtos/user.ts
  src/utils/validate.ts
Labels: ✨ Feat

#208 [MM-309] Fix: Screen 관련 네비게이션 파라미터 에러 수정
  ios/MOIM.xcodeproj/project.pbxproj
  src/apis/moimManage.ts
  src/apis/newFeed/posts.ts
  src/components/calendar/ActiveMoimCard.tsx
  src/components/planCalendar/PlanCalendarEvent.tsx
  src/components/screens/FeedTabScreens/MoimIntroduceEvent.tsx
  src/components/screens/FeedTabScreens/MoimRecommendationEvent.tsx
  src/components/screens/MoimBoardStackScreens/BoardPostPreview.tsx
  src/components/screens/MoimBoardStackScreens/ReadersBottomSheet.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentView.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfo.tsx
  src/components/screens/MoimHomeScreens/MoimPermissionScrollView.tsx
  src/components/screens/NewFeedHomeScreen/NewFeedCard.tsx
  src/hooks/queries/NewFeedHomeScreen/useGetInfinityMoimIntroducePosts.ts
  src/navigators/types/index.ts
  src/screens/CalendarStackScreens/CalendarModifyScreen.tsx
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimBoardStackScreens/MoimParticipantMoimScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostDetailScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostEditScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostReviewScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanDetailScreen.tsx
  src/screens/MoimManagementScreens/DelegationAuthorityScreen.tsx
  src/screens/MoimManagementScreens/JoinManageScreen.tsx
  src/screens/MoimManagementScreens/MoimAddMemberScreen.tsx
  src/screens/MoimManagementScreens/MoimCreateTodoScreen.tsx
  src/screens/MoimManagementScreens/MoimDeleteMemberScreen.tsx
  src/screens/MoimManagementScreens/MoimGetTodoScreen.tsx
  src/screens/MoimManagementScreens/MoimManageListScreen.tsx
  src/screens/MoimManagementScreens/MoimOutMemberScreen.tsx
  src/screens/MoimManagementScreens/MoimTodoDetailScreen.tsx
  src/screens/MoimManagementScreens/MyMoimAssignmentCheckScreen.tsx
  src/screens/MoimManagementScreens/PermissionManageScreen.tsx
  src/screens/MoimManagementScreens/components/ParticipantList.tsx
  src/screens/MoimStackScreens/CalendarTodoDetailScreen.tsx
  src/screens/MoimStackScreens/CalendarWriteScreen.tsx
  src/screens/MyStackScreens/MyDetailProfileScreen.tsx
  src/screens/MyStackScreens/MyHomeScreen.tsx
  src/screens/MyStackScreens/MyReviewScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/MyAssignmentTodoScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/MyTodoDetailScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/TodoAddMemberScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/TodoCreateScreen.tsx
  src/screens/MyStackScreens/TodoStackScreens/TodoMemberDeleteScreen.tsx
  src/screens/NewFeedStack/NewFeedDetailScreen.tsx
  src/screens/NewFeedStack/NewFeedHomeScreen.tsx
  src/screens/UserProfileScreens/UserDetailProfileScreen.tsx
  src/types/dtos/moim.ts
  src/types/dtos/post.ts
  yarn.lock
Labels: 🐞 bug
