Repository M0IM/FE-M, pull requests merged in 2024-08, with the labels that each got.

#31 [MM-61] Navigation Header 구현
  eslint.config.mjs
  src/components/feedTab/FeedTabHeaderLogo.tsx
  src/components/feedTab/FeedTabHeaderRight.tsx
  src/navigators/tab/FeedTabNavigator.tsx
Labels: ✨ Feat

#34 [MM-62] Calendar 컴포넌트 구현
  .yarn/install-state.gz
  ios/Podfile.lock
  package.json
  src/components/@common/CalendarEventList/CalendarEventList.tsx
  src/components/ScreenContainer.tsx
  src/components/calendar/Calendar/Calendar.tsx
  src/components/calendar/Calendar/DateBox.tsx
  src/components/calendar/Calendar/DayOfWeeks.tsx
  src/components/calendar/CalendarEvent/CalendarEvent.tsx
  src/navigators/constants/stack.ts
  src/navigators/stack/AuthStackNavigator.tsx
  src/navigators/stack/CalendarStackNavigator.tsx
  src/navigators/tab/FeedHomeTopTabNavigator.tsx
  src/navigators/tab/FeedTabNavigator.tsx
  src/navigators/types/index.ts
  src/screens/CalendarStackScreens/CalendarDetailScreen.tsx
  src/screens/CalendarStackScreens/CalendarHomeScreen.tsx
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  src/utils/date.ts
  src/utils/index.ts
  tailwind.config.js
  yarn.lock
Labels: ✨ Feat

#37 [MM-65] Feat: Feed Home Screen 컴포넌트 연결
  .yarn/install-state.gz
  src/components/ScreenContainer.tsx
  src/components/home/PostPreviewBox/PostPreviewBox.tsx
  src/components/home/SchduleCard/ScheduleCard.tsx
  src/components/home/ThumbnailBox/ThumbnailBox.tsx
  src/components/screens/FeedTabScreens/MoimHappeningEvent.tsx
  src/components/screens/FeedTabScreens/MoimIntroduceEvent.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/components/screens/FeedTabScreens/MoimRecommendationEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/hooks/queries/AuthScreen/useAuth.ts
  src/navigators/root/RootNavigator.tsx
  src/navigators/stack/CalendarStackNavigator.tsx
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
Labels: ✨ Feat

#36 [MM-63] MM-63-feature/#63 공용 컴포넌트, Moim Space 컴포넌트 구현
  App.tsx
  babel.config.js
  ios/Podfile.lock
  package.json
  src/components/@common/BottomSheetModal/DatePickBottomSheetModal/DatePickBottomSheetModal.tsx
  src/components/@common/CustomBottomSheetModal/CustomBottomSheetModal.stories.tsx
  src/components/@common/CustomBottomSheetModal/CustomBottomSheetModal.tsx
  src/components/@common/FloatingButton/FloatingButton.stories.tsx
  src/components/@common/FloatingButton/FloatingButton.tsx
  src/components/@common/Popover/PopoverMenu/PopoverMenu.stories.tsx
  src/components/@common/Popover/PopoverMenu/PopoverMenu.tsx
  src/components/@common/ScheduleBox/ScheduleBox.stories.tsx
  src/components/@common/ScheduleBox/ScheduleBox.tsx
  src/components/space/DetailSchedules/DetailSchedules.tsx
  src/components/space/SchedulePreviewCard/SchedulePreviewCard.tsx
  src/hooks/usePopover.ts
Labels: ✨ Feat

#40 [MM-66] Feat: MyHomeScreen 컴포넌트 연결 및, 라우팅 연결
  .yarn/install-state.gz
  ios/Podfile.lock
  src/assets/images/Group.png
  src/assets/images/Speech_Bubble.png
  src/assets/images/ion_call.png
  src/components/@common/SettingItem/SettingItem.tsx
  src/components/me/InfoSquareCard/InfoSquareCard.tsx
  src/components/screens/MyStackScreens/MyProfileCard.tsx
  src/hooks/queries/AuthScreen/useAuth.ts
  src/navigators/constants/stack.ts
  src/navigators/stack/MyStackNavigator.tsx
  src/navigators/tab/FeedTabNavigator.tsx
  src/navigators/types/index.ts
  src/screens/FeedTabScreens/MyHomeScreen.tsx
  src/screens/MyStackScreens/AppInfoScreen.tsx
  src/screens/MyStackScreens/EditAlertScreen.tsx
  src/screens/MyStackScreens/EditMoimInfoScreen.tsx
  src/screens/MyStackScreens/MyContactScreen.tsx
  src/screens/MyStackScreens/MyDetailProfileScreen.tsx
  src/screens/MyStackScreens/MyHomeScreen.tsx
  src/screens/MyStackScreens/MyMoimJoinStatusScreen.tsx
  src/screens/MyStackScreens/MyPasswordChangeScreen.tsx
  src/screens/MyStackScreens/MyPrivacyPolicyScreen.tsx
  src/screens/MyStackScreens/MyProfileEditScreen.tsx
  src/screens/MyStackScreens/MyReviewScreen.tsx
  src/screens/MyStackScreens/MyServiceTermScreen.tsx
  src/screens/MyStackScreens/ProfilesScreen.tsx
  src/screens/MyStackScreens/RevokeMoimScreen.tsx
  yarn.lock
Labels: ✨ Feat

#42 [MM-68] Feat: Moim Home Screen 컴포넌트 연결 / 라우팅 연결
  App.tsx
  src/components/calendar/ActiveMoimCard.tsx
  src/components/feedTab/FeedTabHeaderLogo.tsx
  src/components/home/SpacePreviewCard/SpacePreviewCard.tsx
  src/components/screens/MoimHomeScreens/MoimActiveEvent.tsx
  src/navigators/constants/stack.ts
  src/navigators/stack/MoimStackNavigator.tsx
  src/navigators/stack/MyStackNavigator.tsx
  src/navigators/tab/FeedTabNavigator.tsx
  src/navigators/types/index.ts
  src/screens/FeedTabScreens/ChatHomeScreen.tsx
  src/screens/FeedTabScreens/MoimHomeScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/screens/MoimStackScreens/MoimHomeScreen.tsx
  src/screens/MyStackScreens/MyHomeScreen.tsx
Labels: ✨ Feat

#43 [MM-67] MM-67-feature/#67 FeedHomeScreen Style 수정 & CustomTabBar 컴포넌트 구현
  .yarn/install-state.gz
  package.json
  src/components/@common/CustomTabBar/CustomTabBar.tsx
  src/components/ScreenContainer.tsx
  src/components/calendar/Calendar/Calendar.tsx
  src/components/calendar/CalendarEvent/CalendarEvent.tsx
  src/components/feedTab/FeedTabHeaderLogo.tsx
  src/components/feedTab/FeedTabHeaderRight.tsx
  src/components/home/PostPreviewBox/PostPreviewBox.tsx
  src/components/home/RecommendBar/RecommendBar.tsx
  src/components/home/SchduleCard/ScheduleCard.tsx
  src/components/screens/FeedTabScreens/MoimHappeningEvent.tsx
  src/components/screens/FeedTabScreens/MoimIntroduceEvent.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/components/screens/FeedTabScreens/MoimRecommendationEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/navigators/tab/FeedHomeTopTabNavigator.tsx
  src/navigators/tab/FeedTabNavigator.tsx
  yarn.lock
Labels: ✨ Feat

#46 [MM-70] feat: ChatScreen에 관련된 화면을 구현합니다.
  .yarn/install-state.gz
  android/app/src/main/assets/index.android.bundle
  android/app/src/main/res/drawable-hdpi/node_modules_reactnavigation_elements_src_assets_backicon.png
  android/app/src/main/res/drawable-mdpi/node_modules_reactnavigation_elements_src_assets_backicon.png
  android/app/src/main/res/drawable-mdpi/node_modules_reactnavigation_elements_src_assets_backiconmask.png
  android/app/src/main/res/drawable-mdpi/src_assets_images_appleimage.png
  android/app/src/main/res/drawable-mdpi/src_assets_images_googleimage.png
  android/app/src/main/res/drawable-mdpi/src_assets_images_group.png
  android/app/src/main/res/drawable-mdpi/src_assets_images_ion_call.png
  android/app/src/main/res/drawable-mdpi/src_assets_images_kakaoimage.png
  android/app/src/main/res/drawable-mdpi/src_assets_images_naverimage.png
  android/app/src/main/res/drawable-mdpi/src_assets_images_speech_bubble.png
  android/app/src/main/res/drawable-mdpi/src_assets_logos_logogreen.png
  android/app/src/main/res/drawable-mdpi/src_assets_logos_logoicon.png
  android/app/src/main/res/drawable-xhdpi/node_modules_reactnavigation_elements_src_assets_backicon.png
  android/app/src/main/res/drawable-xxhdpi/node_modules_reactnavigation_elements_src_assets_backicon.png
  android/app/src/main/res/drawable-xxxhdpi/node_modules_reactnavigation_elements_src_assets_backicon.png
  src/components/ScreenContainer.tsx
  src/components/swipableChatEvent/SwipableChatEvent.tsx
  src/navigators/constants/stack.ts
  src/navigators/stack/CalendarStackNavigator.tsx
  src/navigators/stack/ChatStackNavigator.tsx
  src/navigators/stack/MoimStackNavigator.tsx
  src/navigators/tab/FeedTabNavigator.tsx
  src/navigators/types/index.ts
  src/screens/ChatStackScreens/ChatHomeScreen.tsx
  src/screens/ChatStackScreens/ChatRoomScreen.tsx
  src/screens/FeedTabScreens/ChatHomeScreen.tsx
Labels: ✨ Feat

#50 [MM-74] Fix: ChatStack 추가, 및 네비게이터 타입 구현
  src/navigators/constants/stack.ts
  src/navigators/types/index.ts
  yarn.lock
Labels: 🐞 bug

#51 [MM-72] 캘린더 페이지 Bottom Sheet 연결, Calendar Write 페이지 라우팅 연결
  .gitignore
  .yarn/install-state.gz
  package.json
  src/components/@common/BottomSheet/BottomSheet.tsx
  src/components/@common/DateBottomSheet/DateSelectorBottomSheet.tsx
  src/components/@common/FloatingButton/FloatingButton.tsx
  src/components/calendar/Calendar/Calendar.tsx
  src/hooks/queries/AuthScreen/useAuth.ts
  src/hooks/useBottomSheet.ts
  src/navigators/constants/stack.ts
  src/navigators/stack/CalendarStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/AuthStackScreens/AuthHomeScreen.tsx
  src/screens/CalendarStackScreens/CalendarHomeScreen.tsx
  src/screens/CalendarStackScreens/CalendarWriteScreen.tsx
  yarn.lock
Labels: ✨ Feat

#55 [MM-77] MM-77-feature/#77 MoimBoardStackScreens 화면 구현
  ios/Podfile.lock
  package.json
  src/components/@common/Popover/PopoverMenu/PopoverMenu.tsx
  src/components/screens/MoimBoardStackScreens/BoardPostPreview.tsx
  src/components/screens/MoimBoardStackScreens/ImagesSlider.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfoContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostRecommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostUserProfile.tsx
  src/navigators/stack/MoimPostStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostDetailScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostEditScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  yarn.lock
Labels: ✨ Feat

#57 [MM-79] MM-79-feature/#79 모임 생성, 모임 찾기 화면 UI
  src/components/@common/CustomTabBar/CustomTabBar.tsx
  src/components/feedTab/FeedTabHeaderRight.tsx
  src/components/screens/MoimCreateScreen/CategoryDropdown.tsx
  src/components/screens/MoimCreateScreen/MoimIntroVideo.tsx
  src/components/screens/MoimCreateScreen/MoimTagContainer.tsx
  src/constants/screens/MoimSearchScreen/CategoryList.ts
  src/hooks/useTags.ts
  src/navigators/constants/stack.ts
  src/navigators/root/RootNavigator.tsx
  src/navigators/stack/HomeStackNavigator.tsx
  src/navigators/tab/FeedTabNavigator.tsx
  src/navigators/tab/MoimTopTabNavigator.tsx
  src/navigators/types/index.ts
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimSearchScreens/MoimSearchScreen.tsx
Labels: ✨ Feat

#59 [MM-81] MM-81-feature/#81 마이페이지 UI 일부 구현
  src/constants/regexps/auth.ts
  src/navigators/constants/stack.ts
  src/navigators/stack/MyStackNavigator.tsx
  src/navigators/stack/my/AppInfoStackNavigator.tsx
  src/navigators/stack/my/RevokeMoimStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MyStackScreens/AppInfoDetailScreen.tsx
  src/screens/MyStackScreens/AppInfoScreen.tsx
  src/screens/MyStackScreens/EditAlertScreen.tsx
  src/screens/MyStackScreens/MyPasswordChangeScreen.tsx
  src/screens/MyStackScreens/MyPrivacyPolicyScreen.tsx
  src/screens/MyStackScreens/MyServiceTermScreen.tsx
  src/screens/MyStackScreens/RevokeMoimDetailScreen.tsx
  src/screens/MyStackScreens/RevokeMoimScreen.tsx
Labels: ✨ Feat

#62 [MM-84] Fix: types/index.ts 충돌 수정
  .yarn/install-state.gz
  src/navigators/types/index.ts
  yarn.lock
Labels: 🐞 bug

#64 [MM-84] Feature: usePermission, useImagePicker, useAppState 공용 훅 생성.
  .yarn/install-state.gz
  App.tsx
  android/app/build.gradle
  android/build.gradle
  ios/MOIM.xcodeproj/project.pbxproj
  ios/MOIM/Info.plist
  ios/MOIM/PrivacyInfo.xcprivacy
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/apis/image.ts
  src/components/@common/ImageInput/ImageInput.tsx
  src/components/post/PostForm.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/components/screens/MoimWriteScreen/ScheduleEditEvent.tsx
  src/components/screens/MoimWriteScreen/ScheduleEvent.tsx
  src/constants/message.ts
  src/hooks/queries/MoimCreateScreen/useMutateImages.ts
  src/hooks/useAppState.ts
  src/hooks/useImagePicker.ts
  src/hooks/usePermission.ts
  src/navigators/stack/HomeStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimSearchScreens/MoimSearchScreen.tsx
  src/types/domain.ts
  src/utils/image.ts
  src/utils/index.ts
  src/utils/time.ts
  yarn.lock
Labels: ✨ Feat

#69 [MM-96] 마이페이지 관련 유저 API 연결
  App.tsx
  ios/MOIM.xcodeproj/project.pbxproj
  src/apis/auth.ts
  src/apis/index.ts
  src/apis/user.ts
  src/components/screens/MyStackScreens/MyProfileCard.tsx
  src/components/screens/MyStackScreens/ReviewCard.tsx
  src/hooks/queries/MyScreen/useGetInfiniteMyDetailReviews.ts
  src/hooks/queries/MyScreen/useGetProfile.ts
  src/navigators/types/index.ts
  src/screens/AuthStackScreens/AuthHomeScreen.tsx
  src/screens/MyStackScreens/MyHomeScreen.tsx
  src/screens/MyStackScreens/MyReviewScreen.tsx
  src/types/dtos/user.ts
Labels: ✨ Feat

#68 [MM-94] 알림 화면 UI 구현 & 모임 네비게이터 수정
  ios/Podfile.lock
  package.json
  src/components/@common/CustomTabBar/CustomTabBar.tsx
  src/components/calendar/ActiveMoimCard.tsx
  src/components/feedTab/FeedTabHeaderRight.tsx
  src/components/screens/MoimHomeScreens/MoimActiveEvent.tsx
  src/navigators/stack/HomeStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimBoardStackScreens/MoimPostDetailScreen.tsx
  src/screens/MoimStackScreens/MoimHomeScreen.tsx
  src/screens/PushAlertScreens/PushAlertScreen.tsx
  src/utils/date.ts
  yarn.lock
Labels: ✨ Feat

#73 [MM-100] 유저 프로필 수정 페이지 구현 및 API 연결
  .yarn/install-state.gz
  src/apis/image.ts
  src/apis/user.ts
  src/components/@common/Avatar/Avatar.tsx
  src/components/screens/MyStackScreens/MyProfileCard.tsx
  src/hooks/queries/MyScreen/useCreatePresignedURL.ts
  src/hooks/queries/MyScreen/useGetDetailProfile.ts
  src/hooks/queries/MyScreen/useGetInfiniteMyDetailReviews.ts
  src/hooks/queries/MyScreen/useGetProfile.ts
  src/hooks/queries/MyScreen/useUpdateMyProfile.ts
  src/hooks/useImagePicker.ts
  src/navigators/types/index.ts
  src/screens/AuthStackScreens/AuthHomeScreen.tsx
  src/screens/AuthStackScreens/LoginScreen.tsx
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/screens/MyStackScreens/MyDetailProfileScreen.tsx
  src/screens/MyStackScreens/MyProfileEditScreen.tsx
  src/screens/MyStackScreens/MyReviewScreen.tsx
  src/stores/useDetailProfileStore.ts
  src/types/dtos/image.ts
  src/types/dtos/user.ts
  src/utils/date.ts
  src/utils/image.ts
  src/utils/validate.ts
  yarn.lock
Labels: ✨ Feat

#72 [MM-101] MM-101-feature/#101 모임 관리 화면 UI 구현
  src/components/@common/CustomTabBar/CustomTabBar.tsx
  src/components/screens/MoimCreateScreen/CategoryDropdown.tsx
  src/constants/screens/MoimSearchScreen/CategoryList.ts
  src/navigators/constants/stack.ts
  src/navigators/stack/MoimManagementStackNavigator.tsx
  src/navigators/stack/MoimPlanStackNavigator.tsx
  src/navigators/stack/MoimPostStackNavigator.tsx
  src/navigators/tab/MoimTopTabNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanHomeScreen.tsx
  src/screens/MoimManagementScreens/JoinManageScreen.tsx
  src/screens/MoimManagementScreens/MoimInfoEditScreen.tsx
  src/screens/MoimManagementScreens/MoimManageListScreen.tsx
  src/screens/MoimManagementScreens/PermissionManageScreen.tsx
Labels: ✨ Feat

#76 [MM-116] MM-116-feature/#116 모임 정보 수정 & 모임 신청 상태 확인 UI, 모임 생성 화면 수정
  src/navigators/stack/MoimManagementStackNavigator.tsx
  src/navigators/stack/MyStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimManagementScreens/MoimEditInfoScreen.tsx
  src/screens/MyStackScreens/EditMoimInfoScreen.tsx
  src/screens/MyStackScreens/MyMoimJoinStatusScreen.tsx
  yarn.lock
Labels: ✨ Feat

#82 [MM-119] 모임 관련 API 연결 (무한스크롤 적용), 모임 세부 일정 UI 변경
  .yarn/install-state.gz
  react-native-config.d.ts
  src/apis/calendar.ts
  src/apis/image.ts
  src/apis/search.ts
  src/components/@common/CalendarEventList/CalendarEventList.tsx
  src/components/@common/SearchInput/SearchInput.tsx
  src/components/calendar/ActiveMoimCard.tsx
  src/components/calendar/CalendarEvent/CalendarEvent.tsx
  src/components/calendar/CalendarPostForm.tsx
  src/components/home/SpaceCard/SpaceCard.tsx
  src/components/myCalendarBottomSheet/myCalendarBottomSheet.tsx
  src/components/planCalendar/PlanCalendarEvent.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/components/screens/MoimPlanDetailScreen/ParticipantList.tsx
  src/components/screens/MyStackScreens/MyProfileCard.tsx
  src/components/swipableChatEvent/SwipableChatEvent.tsx
  src/constants/screens/MoimSearchScreen/CategoryList.ts
  src/hooks/queries/CalendarHomeScreen/useDeleteMyCalendarSchedule.ts
  src/hooks/queries/CalendarHomeScreen/usePostMyCalendarSchedule.ts
  src/hooks/queries/CalendarHomeScreen/useUpdateMyCalendarSchedule.ts
  src/hooks/queries/MoimSearchScreen/useGetSeachInfiniteMoimList.ts
  src/hooks/queries/MyScreen/useUpdateMyProfile.ts
  src/hooks/useDebounce.ts
  src/hooks/useSearchMoim.ts
  src/navigators/stack/CalendarStackNavigator.tsx
  src/navigators/tab/MoimTopTabNavigator.tsx
  src/navigators/types/index.ts
  src/screens/CalendarStackScreens/CalendarDetailScreen.tsx
  src/screens/CalendarStackScreens/CalendarHomeScreen.tsx
  src/screens/CalendarStackScreens/CalendarModifyScreen.tsx
  src/screens/CalendarStackScreens/CalendarWriteScreen.tsx
  src/screens/MoimSearchScreens/MoimSearchScreen.tsx
  src/screens/MyStackScreens/MyDetailProfileScreen.tsx
  src/screens/MyStackScreens/MyProfileEditScreen.tsx
  src/stores/useDetailProfileStore.ts
  src/stores/useMyCalendarStore.ts
  src/types/dtos/calendar.ts
  src/types/dtos/moim.ts
  src/types/enums/index.ts
  src/utils/image.ts
  src/utils/validate.ts
  yarn.lock
Labels: ✨ Feat

#80 [MM-117] 모임 게시글 관련 API 연결
  src/apis/post.ts
  src/components/@common/Dropdown/CustomDropdown.tsx
  src/components/screens/MoimBoardStackScreens/BoardPostPreview.tsx
  src/components/screens/MoimBoardStackScreens/ReadersBottomSheet.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfoContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostRecommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostUserProfile.tsx
  src/constants/screens/MoimBoardStackScreens/PostList.ts
  src/hooks/queries/MoimBoard/usePost.ts
  src/hooks/useDropdown.ts
  src/navigators/types/index.ts
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostDetailScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  src/types/dtos/post.ts
Labels: ✨ Feat

#84 [MM-122] 모임 관리 API 연결
  src/apis/auth.ts
  src/apis/moimManage.ts
  src/hooks/queries/MoimManagement/useMoimManagement.ts
  src/screens/MoimManagementScreens/JoinManageScreen.tsx
  src/screens/MoimManagementScreens/MoimEditInfoScreen.tsx
  src/screens/MoimManagementScreens/PermissionManageScreen.tsx
  src/types/dtos/moimManage.ts
Labels: ✨ Feat

#87 [MM-135] 모임 스페이스 버그 수정
  src/hooks/queries/MoimBoard/usePost.ts
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimManagementScreens/MoimEditInfoScreen.tsx
Labels: 🐞 bug

#90 [MM-137] 마이페이지 관련 API 연결
  .yarn/install-state.gz
  package.json
  src/apis/alert.ts
  src/apis/index.ts
  src/components/post/PostForm.tsx
  src/hooks/queries/MyScreen/useGetAlertStatus.ts
  src/hooks/queries/MyScreen/usePostEventAlertStatus.ts
  src/hooks/queries/MyScreen/usePostPushAlertStatus.ts
  src/screens/MyStackScreens/EditAlertScreen.tsx
  src/types/dtos/alert.ts
  src/types/dtos/calendar.ts
  yarn.lock
Labels: ✨ Feat

#92 [MM-136] Feat: 게시글 관련 API 연결
  src/apis/post.ts
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostRecommentContainer.tsx
  src/hooks/queries/MoimBoard/usePost.ts
  src/hooks/useImagePicker.ts
  src/navigators/types/index.ts
  src/screens/MoimBoardStackScreens/MoimPostDetailScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostEditScreen.tsx
  src/types/dtos/post.ts
Labels: ✨ Feat

#97 Mm 140 feature/#140
  ios/MOIM/Info.plist
  src/apis/auth.ts
  src/apis/calendar.ts
  src/apis/chat.ts
  src/components/post/PostForm.tsx
  src/components/swipableChatEvent/SwipableChatEvent.tsx
  src/hooks/queries/AuthScreen/useAuth.ts
  src/hooks/queries/ChatHomeScreen/useGetChatList.ts
  src/hooks/queries/MoimPlanDetailScreen/useDeleteDetailMoimCalendar.ts
  src/hooks/useSocket.ts
  src/hooks/useSocketService.ts
  src/navigators/root/RootNavigator.tsx
  src/screens/AuthStackScreens/AuthHomeScreen.tsx
  src/screens/AuthStackScreens/SignupLastStepScreen.tsx
  src/screens/ChatStackScreens/ChatRoomScreen.tsx
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanDetailScreen.tsx
  src/screens/MyStackScreens/MyHomeScreen.tsx
  src/types/dtos/auth.ts
  src/types/dtos/chat.ts
Labels: ✨ Feat

#100 [MM-144] 메인 페이지 API 및 이미지 연결
  .yarn/install-state.gz
  src/apis/calendar.ts
  src/components/calendar/ActiveMoimCard.tsx
  src/components/calendar/Calendar/DateBox.tsx
  src/components/calendar/Calendar/MoimCalendar.tsx
  src/components/calendar/CalendarPostForm.tsx
  src/components/home/RecommendBar/RecommendBar.tsx
  src/components/home/SchduleCard/ScheduleCard.tsx
  src/components/home/SpaceCard/SpaceCard.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/hooks/queries/FeedHome/useGetUserSchedulesCount.ts
  src/hooks/queries/FeedHome/useGetUserTodayParticipantSchedules.ts
  src/hooks/queries/FeedHome/useGetUserTodaySchedules.ts
  src/hooks/useSocketService.ts
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  src/screens/MoimManagementScreens/PermissionManageScreen.tsx
  src/types/dtos/calendar.ts
  src/types/dtos/moim.ts
  yarn.lock
Labels: ✨ Feat

#101 [MM-143] Feat: 모임 스페이스, 모임 관리 API 연결
  src/apis/moim.ts
  src/apis/moimManage.ts
  src/components/screens/MoimDetailScreen/MoimDashboardContainer.tsx
  src/components/screens/MoimDetailScreen/MoimImageBox.tsx
  src/components/screens/MoimDetailScreen/MoimInfoContainer.tsx
  src/components/screens/MoimDetailScreen/MoimMemberBottomSheet.tsx
  src/constants/screens/MoimSearchScreen/CategoryList.ts
  src/hooks/queries/MoimManagement/useMoimManagement.ts
  src/hooks/queries/MoimSpace/useGetInfinityMoimMembers.ts
  src/hooks/queries/MoimSpace/useGetMoimSpaceInfo.ts
  src/hooks/queries/MoimSpace/useRequestMoimJoin.ts
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimManagementScreens/JoinManageScreen.tsx
  src/screens/MoimManagementScreens/MoimEditInfoScreen.tsx
  src/screens/MoimManagementScreens/PermissionManageScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/types/dtos/moim.ts
  src/types/dtos/moimManage.ts
Labels: ✨ Feat

#104 [MM-152] 모임 탈퇴 API 구현
  .yarn/install-state.gz
  ios/Podfile.lock
  package.json
  src/apis/moim.ts
  src/components/@common/Avatar/Avatar.tsx
  src/components/calendar/ActiveMoimCard.tsx
  src/components/home/SpaceCard/SpaceCard.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/hooks/queries/MyScreen/useWithdrawMoim.ts
  src/navigators/stack/my/RevokeMoimStackNavigator.tsx
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  src/screens/MoimStackScreens/MoimHomeScreen.tsx
  src/screens/MyStackScreens/RevokeMoimDetailScreen.tsx
  src/screens/MyStackScreens/RevokeMoimScreen.tsx
  src/types/dtos/moim.ts
  yarn.lock
Labels: ✨ Feat

#106 [MM-154] Feature: FCM TOKEN 기능구현 / Auth API 변경사항 반영
  .yarn/install-state.gz
  App.tsx
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/colors.xml
  android/build.gradle
  ios/GoogleService-Info.plist
  ios/MOIM.xcodeproj/project.pbxproj
  ios/MOIM/AppDelegate.h
  ios/MOIM/AppDelegate.mm
  ios/MOIM/Info.plist
  ios/MOIM/MOIM.entitlements
  ios/MOIM/PrivacyInfo.xcprivacy
  ios/Podfile
  ios/Podfile.lock
  ios/true
  package.json
  src/apis/auth.ts
  src/screens/AuthStackScreens/AuthHomeScreen.tsx
  src/screens/AuthStackScreens/LoginScreen.tsx
  src/stores/useFcmTokenStore.ts
  src/types/dtos/auth.ts
  yarn.lock
Labels: ✨ Feat

#108 Mm 161 feature/#161
  ios/MOIM.xcodeproj/project.pbxproj
  src/apis/calendar.ts
  src/components/calendar/CalendarPostForm.tsx
  src/components/home/MoimWriteBar/MoimWriteBar.tsx
  src/components/home/SchduleCard/ScheduleCard.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/hooks/queries/CalendarHomeScreen/usePostMyCalendarSchedule.ts
  src/hooks/queries/FeedHome/useGetInfiniteAllUserSchedule.ts
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  src/types/dtos/calendar.ts
  src/utils/validate.ts
Labels: ✨ Feat

#111 [MM-151] Feat: 게시글 로직 수정 및 스타일 수정
  ios/Podfile.lock
  src/assets/icons/user.png
  src/components/@common/Avatar/Avatar.tsx
  src/components/@common/Dropdown/CustomDropdown.tsx
  src/components/screens/MoimBoardStackScreens/BoardPostPreview.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfoContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostRecommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostUserProfile.tsx
  src/components/screens/MoimDetailScreen/MoimDashboardContainer.tsx
  src/navigators/types/index.ts
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostDetailScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostEditScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/utils/date.ts
Labels: 🐞 bug, ✨ Feat

#114 [MM-166] Fix: 아바타 Props 에러 수정
  ios/MOIM.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/components/@common/Avatar/Avatar.tsx
  yarn.lock
Labels: 🐞 bug

#116 [MM-167] Feat: 모임 소개 스크린 연결 및, 게시물 상세 조회 API 연결
  .yarn/install-state.gz
  App.tsx
  ios/MOIM.xcodeproj/project.pbxproj
  src/apis/auth.ts
  src/apis/newFeed/posts.ts
  src/apis/post.ts
  src/components/calendar/ActiveMoimCard.tsx
  src/components/calendar/CalendarEvent/CalendarEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/components/screens/NewFeedHomeScreen/NewFeedCard.tsx
  src/hooks/queries/CalendarHomeScreen/useGetPersonalCalendar.ts
  src/hooks/queries/NewFeedHomeScreen/useGetInfinityMoimIntroducePosts.ts
  src/navigators/constants/stack.ts
  src/navigators/stack/NewFeedHomeStack.tsx
  src/navigators/tab/FeedTabNavigator.tsx
  src/navigators/types/index.ts
  src/screens/AuthStackScreens/AuthHomeScreen.tsx
  src/screens/AuthStackScreens/SignupLastStepScreen.tsx
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  src/screens/MoimSearchScreens/MoimSearchScreen.tsx
  src/screens/NewFeedStack/NewFeedDetailScreen.tsx
  src/screens/NewFeedStack/NewFeedHomeScreen.tsx
  src/types/dtos/moim.ts
  yarn.lock
Labels: ✨ Feat

#119 [MM-169] Feat: NewFeed Screen 디자인 변경, Skeleton UI 적용
  .yarn/install-state.gz
  package.json
  src/components/screens/NewFeedHomeScreen/NewFeedCard.tsx
  src/components/screens/NewFeedHomeScreen/skeleton/NewFeedCardSkeleton.tsx
  src/navigators/stack/NewFeedHomeStack.tsx
  src/navigators/tab/FeedTabNavigator.tsx
  src/screens/NewFeedStack/NewFeedHomeScreen.tsx
  yarn.lock
Labels: ✨ Feat

#118 [MM-165] Feat: 모임스페이스 연결 & 게시글 오류 수정
  src/components/@common/CalendarEventList/PlanCalendarEventList.tsx
  src/components/@common/CustomTabBar/CustomTabBar.tsx
  src/components/@common/Popover/PopoverMenu/PopoverMenu.tsx
  src/components/post/PostForm.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfoContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostRecommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostUserProfile.tsx
  src/components/screens/MoimDetailScreen/MoimContentsPreview.tsx
  src/components/screens/MoimDetailScreen/MoimInfoContainer.tsx
  src/components/space/SchedulePreviewCard/SchedulePreviewCard.tsx
  src/hooks/queries/MoimPlanHomeScreen/useGetMoimCalendar.ts
  src/navigators/stack/MoimPlanStackNavigator.tsx
  src/navigators/stack/MoimPostStackNavigator.tsx
  src/navigators/stack/MoimStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostDetailScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanDetailScreen.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanHomeScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/screens/MoimStackScreens/MoimWriteScreen.tsx
  src/types/dtos/moim.ts
Labels: 🐞 bug, ✨ Feat

#122 [MM-171] Feat: 메인 화면 연결 및 UI 구현
  .yarn/install-state.gz
  src/apis/calendar.ts
  src/apis/moim.ts
  src/components/ScreenContainer.tsx
  src/components/home/PostPreviewBox/PostPreviewBox.tsx
  src/components/screens/FeedTabScreens/AllMoimPost.tsx
  src/components/screens/FeedTabScreens/MoimFeedPreview.tsx
  src/components/screens/FeedTabScreens/MoimHappeningEvent.tsx
  src/components/screens/FeedTabScreens/MoimMyEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/hooks/queries/FeedHome/useGetMoimAllPosts.ts
  src/navigators/stack/HomeStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanHomeScreen.tsx
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/types/dtos/moim.ts
  yarn.lock
Labels: ✨ Feat

#126 [MM-180] NewFeedHome Screen을 리디자인했습니다.
  .yarn/install-state.gz
  src/apis/post.ts
  src/components/CommentBottomSheet/CommentBottomSheet.tsx
  src/components/post/PostForm.tsx
  src/components/screens/FeedTabScreens/MoimFeedPreview.tsx
  src/components/screens/NewFeedHomeScreen/NewFeedCard.tsx
  src/hooks/queries/NewFeedDetailScreen/useGetDetailMoimIntroducePost.ts
  src/hooks/queries/NewFeedHomeScreen/useGetInfinityMoimIntroducePosts.ts
  src/screens/MoimBoardStackScreens/components/CommentInput.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanHomeScreen.tsx
  src/screens/NewFeedStack/NewFeedDetailScreen.tsx
  src/screens/NewFeedStack/NewFeedHomeScreen.tsx
  src/types/dtos/moim.ts
  src/types/dtos/post.ts
  yarn.lock
Labels: ✨ Feat

#127 [MM-182] Feat: 모임 스페이스 로직 변경 & 마이페이지 UI 수정 및 API 연결
  ios/Podfile.lock
  package.json
  src/apis/user.ts
  src/components/@common/CustomTabBar/CustomTabBar.tsx
  src/components/@common/ProfileCard/ProfileCard.tsx
  src/components/@common/SettingItem/SettingItem.tsx
  src/components/me/InfoSquareCard/InfoSquareCard.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostRecommentContainer.tsx
  src/components/screens/MoimDetailScreen/MoimContentsPreview.tsx
  src/components/screens/MoimDetailScreen/MoimInfoContainer.tsx
  src/components/screens/MyStackScreens/MyProfileCard.tsx
  src/constants/screens/MyScreens/MoimJoinStatus.ts
  src/constants/screens/MyScreens/MyPrivacyPolicyScreen.ts
  src/constants/screens/MyScreens/MyServiceTermScreen.ts
  src/hooks/queries/MyScreen/useGetInfiniteMoimJoinRequest.ts
  src/navigators/stack/MyStackNavigator.tsx
  src/navigators/tab/MoimTopTabNavigator.tsx
  src/screens/MoimBoardStackScreens/MoimPostDetailScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/screens/MyStackScreens/MyContactScreen.tsx
  src/screens/MyStackScreens/MyDetailProfileScreen.tsx
  src/screens/MyStackScreens/MyHomeScreen.tsx
  src/screens/MyStackScreens/MyMoimJoinStatusScreen.tsx
  src/screens/MyStackScreens/MyPrivacyPolicyScreen.tsx
  src/screens/MyStackScreens/MyServiceTermScreen.tsx
  src/types/dtos/moim.ts
  src/types/dtos/moimManage.ts
  src/types/dtos/post.ts
  src/types/dtos/user.ts
  src/types/enums/index.ts
  yarn.lock
Labels: ✨ Feat

#130 [MM-191] FeedHomeScreen API 변경사항 반영
  .yarn/install-state.gz
  src/apis/calendar.ts
  src/components/screens/FeedTabScreens/MoimHappeningEvent.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/hooks/queries/FeedHome/useGetInfiniteAllUserSchedule.ts
  src/navigators/stack/CalendarStackNavigator.tsx
  src/screens/FeedTabScreens/FeedHomeScreen.tsx
  yarn.lock
Labels: ✨ Feat

#132 [MM-192] Calendar API 연결, 일정 DetailPage, 지역정보 API 연결, 자잘한 수정, 가로 막기
  android/app/src/main/AndroidManifest.xml
  ios/MOIM/Info.plist
  src/apis/calendar.ts
  src/apis/index.ts
  src/apis/post.ts
  src/apis/region.ts
  src/components/@common/CalendarEventList/CalendarEventList.tsx
  src/components/@common/DatePickerOption/DatePickerOption.tsx
  src/components/@common/SearchInput/SearchInput.tsx
  src/components/RegionPickerOption/RegionPickerOption.tsx
  src/components/calendar/Calendar/DateBox.tsx
  src/components/calendar/Calendar/MoimCalendar.tsx
  src/components/calendar/CalendarEvent/CalendarEvent.tsx
  src/components/calendar/CalendarPostForm.tsx
  src/components/home/SchduleCard/ScheduleCard.tsx
  src/components/planCalendar/PlanCalendarEvent.tsx
  src/components/post/PostForm.tsx
  src/components/screens/FeedTabScreens/MoimScheduleEvent.tsx
  src/components/screens/MoimDetailScreen/MoimMemberBottomSheet.tsx
  src/components/screens/MoimPlanDetailScreen/ParticipantList.tsx
  src/components/space/DetailSchedules/DetailSchedules.tsx
  src/hooks/queries/AuthScreen/useAuth.ts
  src/hooks/queries/MoimStack/useGetDetailIndividualSchedule.ts
  src/hooks/queries/MoimStack/useGetDetailMoimParticipantSchedule.ts
  src/hooks/queries/Region/useGetInfinityRegion.ts
  src/navigators/stack/CalendarStackNavigator.tsx
  src/navigators/stack/HomeStackNavigator.tsx
  src/navigators/types/index.ts
  src/screens/AuthStackScreens/AuthHomeScreen.tsx
  src/screens/AuthStackScreens/PrivacyPolicyScreen.tsx
  src/screens/AuthStackScreens/ServiceTermScreen.tsx
  src/screens/AuthStackScreens/SignupLastStepScreen.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanDetailScreen.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanHomeScreen.tsx
  src/screens/MoimStackScreens/CalendarIndividualDetailScreen.tsx
  src/screens/MoimStackScreens/CalendarParticipantDetailScreen.tsx
  src/screens/MoimStackScreens/CalendarWriteScreen.tsx
  src/screens/MoimStackScreens/components/DetailItem.tsx
  src/screens/MyStackScreens/MyDetailProfileScreen.tsx
  src/types/dtos/calendar.ts
  src/types/dtos/region.ts
  src/utils/validate.ts
Labels: ✨ Feat

#138 [MM-198] Feat: 모임 스페이스 UI/UX 개선
  src/components/@common/CustomButton/CustomButton.tsx
  src/components/screens/MoimBoardStackScreens/BoardPostPreview.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/CommentInput.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfo.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/skeleton/PostInfoSkeleton.tsx
  src/components/screens/MoimDetailScreen/MoimMemberBottomSheet.tsx
  src/components/screens/MoimDetailScreen/MoimMembersScrollView.tsx
  src/components/screens/MoimDetailScreen/MoimMembersView.tsx
  src/components/screens/MoimHomeScreens/MoimJoinRequestScrollView.tsx
  src/components/screens/MoimHomeScreens/MoimPermissionScrollView.tsx
  src/components/screens/MoimHomeScreens/Skeleton/MoimBoardSkeleton.tsx
  src/components/screens/MoimHomeScreens/Skeleton/MoimDetailSkeleton.tsx
  src/screens/MoimBoardStackScreens/MoimBoardScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostEditScreen.tsx
  src/screens/MoimBoardStackScreens/MoimPostWriteScreen.tsx
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimManagementScreens/JoinManageScreen.tsx
  src/screens/MoimManagementScreens/MoimEditInfoScreen.tsx
  src/screens/MoimManagementScreens/PermissionManageScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/utils/wait.ts
Labels: 🐞 bug, ✨ Feat

#143 [MM-205] 반응형 UI 수정
  .yarn/install-state.gz
  ios/MOIM.xcodeproj/project.pbxproj
  src/components/@common/ProfileCard/ProfileCard.tsx
  src/components/calendar/CalendarPostForm.tsx
  src/screens/MyStackScreens/MyDetailProfileScreen.tsx
  src/screens/MyStackScreens/MyProfileEditScreen.tsx
  src/types/dtos/user.ts
Labels: ✨ Feat, 🌏 Deploy, 🎨 Style

#142 [MM-204] Feat: 모임 스페이스&일정 관련 버그 및 스타일 수정 (아직 머지 X)
  src/apis/moimManage.ts
  src/components/post/PostForm.tsx
  src/components/screens/MoimBoardStackScreens/BoardPostPreview.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfoContainer.tsx
  src/components/screens/MoimCalenderScreen/MoimPlanDetailSkeleton.tsx
  src/components/screens/MoimDetailScreen/MoimContentsPreview.tsx
  src/components/screens/MoimDetailScreen/MoimInfoContainer.tsx
  src/components/screens/MoimWriteScreen/ScheduleEditEvent.tsx
  src/components/space/DetailSchedules/DetailSchedules.tsx
  src/constants/screens/MoimSearchScreen/CategoryList.ts
  src/navigators/tab/FeedTabNavigator.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanDetailScreen.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanHomeScreen.tsx
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimManagementScreens/MoimEditInfoScreen.tsx
  src/screens/MoimStackScreens/MoimDetailScreen.tsx
  src/types/dtos/calendar.ts
  src/types/dtos/moimManage.ts
  src/types/dtos/post.ts
Labels: 🐞 bug, ✨ Feat, 🎨 Style

#146 [MM-212] Feat: 모임&프로필 버그 및 스타일 수정
  ios/Podfile.lock
  src/components/@common/SelectRegionBottomSheet/SelectRegionBottomSheet.tsx
  src/components/screens/MoimBoardStackScreens/ReadersBottomSheet.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfo.tsx
  src/components/screens/MoimDetailScreen/MoimImageBox.tsx
  src/screens/MoimCalenderStackScreens/MoimPlanDetailScreen.tsx
  src/screens/MoimCreateScreens/MoimCreateScreen.tsx
  src/screens/MoimManagementScreens/MoimEditInfoScreen.tsx
  src/screens/MyStackScreens/MyProfileEditScreen.tsx
  yarn.lock
Labels: 🐞 bug, ✨ Feat, 🌏 Deploy, 🎨 Style

#152 [MM-224] 배포 이전 에러 수정
  App.tsx
  ios/MOIM.xcodeproj/project.pbxproj
  ios/MOIM/Info.plist
  ios/MOIM/MOIM.entitlements
  ios/MOIM/main.m
  src/apis/auth.ts
  src/components/@common/ProfileCard/ProfileCard.tsx
  src/components/screens/MoimBoardStackScreens/BoardPostPreview.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostCommentContainer.tsx
  src/components/screens/MoimBoardStackScreens/postDetail/PostInfo.tsx
  src/components/screens/MoimHomeScreens/MoimJoinRequestScrollView.tsx
  src/components/screens/MoimHomeScreens/MoimPermissionScrollView.tsx
  src/components/screens/MyStackScreens/MyProfileCard.tsx
  src/hooks/queries/AuthScreen/useAuth.ts
  src/navigators/root/RootNavigator.tsx
  src/screens/AuthStackScreens/AuthHomeScreen.tsx
  src/screens/AuthStackScreens/SignupLastStepScreen.tsx
  src/screens/MoimBoardStackScreens/MoimMemberDetailProfileScreen.tsx
  src/screens/MoimManagementScreens/DelegationAuthorityScreen.tsx
  src/screens/MyStackScreens/MyProfileEditScreen.tsx
  src/screens/MyStackScreens/RevokeMoimDetailScreen.tsx
  src/types/dtos/auth.ts
Labels: 🐞 bug, ✨ Feat, 🔨 Refactor, 🌏 Deploy
